USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE MARKETING_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE FINANCE_WH
WITH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE ETL_WH
WITH
WAREHOUSE_SIZE = 'MEDIUM'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;


CREATE OR REPLACE ROLE MARKETING_ANALYST;
CREATE OR REPLACE ROLE FINANCE_USER;
CREATE OR REPLACE ROLE ETL_DEVELOPER;


GRANT USAGE ON WAREHOUSE MARKETING_WH
TO ROLE MARKETING_ANALYST;

GRANT USAGE ON WAREHOUSE FINANCE_WH
TO ROLE FINANCE_USER;

GRANT USAGE ON WAREHOUSE ETL_WH
TO ROLE ETL_DEVELOPER;


CREATE OR REPLACE USER MKT_USER1
PASSWORD = 'Marketing@123'
DEFAULT_ROLE = MARKETING_ANALYST
DEFAULT_WAREHOUSE = MARKETING_WH
MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER FIN_USER1
PASSWORD = 'Finance@123'
DEFAULT_ROLE = FINANCE_USER
DEFAULT_WAREHOUSE = FINANCE_WH
MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER ETL_USER1
PASSWORD = 'ETL@123'
DEFAULT_ROLE = ETL_DEVELOPER
DEFAULT_WAREHOUSE = ETL_WH
MUST_CHANGE_PASSWORD = FALSE;


GRANT ROLE MARKETING_ANALYST TO USER MKT_USER1;

GRANT ROLE FINANCE_USER TO USER FIN_USER1;

GRANT ROLE ETL_DEVELOPER TO USER ETL_USER1;


CREATE OR REPLACE DATABASE RETAIL_MARKETING_DB;

USE DATABASE RETAIL_MARKETING_DB;

CREATE OR REPLACE SCHEMA SALES_SCHEMA;

USE SCHEMA SALES_SCHEMA;


CREATE OR REPLACE TABLE CAMPAIGN_SALES AS
SELECT
    SS.ss_sold_date_sk,
    D.d_date AS SALE_DATE,
    C.c_customer_sk,
    C.c_first_name,
    C.c_last_name,
    I.i_item_sk,
    I.i_item_desc,
    I.i_category,
    SS.ss_quantity,
    SS.ss_sales_price,
    SS.ss_net_profit
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES SS
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER C
    ON SS.ss_customer_sk = C.c_customer_sk
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM D
    ON SS.ss_sold_date_sk = D.d_date_sk
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM I
    ON SS.ss_item_sk = I.i_item_sk
LIMIT 100000;


GRANT USAGE ON DATABASE RETAIL_MARKETING_DB
TO ROLE MARKETING_ANALYST;

GRANT USAGE ON DATABASE RETAIL_MARKETING_DB
TO ROLE FINANCE_USER;

GRANT USAGE ON DATABASE RETAIL_MARKETING_DB
TO ROLE ETL_DEVELOPER;


GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.SALES_SCHEMA
TO ROLE MARKETING_ANALYST;

GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.SALES_SCHEMA
TO ROLE FINANCE_USER;

GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.SALES_SCHEMA
TO ROLE ETL_DEVELOPER;


GRANT SELECT ON TABLE RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
TO ROLE MARKETING_ANALYST;

GRANT SELECT ON TABLE RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
TO ROLE FINANCE_USER;


GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA RETAIL_MARKETING_DB.SALES_SCHEMA
TO ROLE ETL_DEVELOPER;

GRANT CREATE TABLE
ON SCHEMA RETAIL_MARKETING_DB.SALES_SCHEMA
TO ROLE ETL_DEVELOPER;


USE WAREHOUSE MARKETING_WH;


ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'XSMALL';

SELECT
    i_category,
    SUM(ss_sales_price) AS TOTAL_SALES,
    SUM(ss_net_profit) AS TOTAL_PROFIT
FROM RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
GROUP BY i_category
ORDER BY TOTAL_SALES DESC;


ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'SMALL';


SELECT
    i_category,
    SUM(ss_sales_price) AS TOTAL_SALES,
    SUM(ss_net_profit) AS TOTAL_PROFIT
FROM RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
GROUP BY i_category
ORDER BY TOTAL_SALES DESC;


ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'XSMALL';


SELECT
    i_category,
    SUM(ss_sales_price) AS TOTAL_SALES
FROM RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
GROUP BY i_category;


SELECT
    i_category,
    SUM(ss_sales_price) AS TOTAL_SALES
FROM RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
GROUP BY i_category;


SELECT
    SALE_DATE,
    SUM(ss_sales_price) AS TOTAL_SALES
FROM RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
WHERE SALE_DATE BETWEEN '2001-01-01' AND '2001-03-31'
GROUP BY SALE_DATE
ORDER BY SALE_DATE;


ALTER TABLE RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
CLUSTER BY (SALE_DATE);


SELECT
    SALE_DATE,
    SUM(ss_sales_price) AS TOTAL_SALES
FROM RETAIL_MARKETING_DB.SALES_SCHEMA.CAMPAIGN_SALES
WHERE SALE_DATE BETWEEN '2001-01-01' AND '2001-03-31'
GROUP BY SALE_DATE
ORDER BY SALE_DATE;